---
title: "Strings and Factors"
author: "Miriam Lachs"
date: "2024-10-15"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

library(p8105.datasets)
```

## Let's do strings

```{r}
string_vec = c("my", "name", "is", "miriam")

str_detect(string_vec, "miriam")

str_replace(string_vec, "miriam", "Miriam")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")

str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Pp]umpkin")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
```

How things start to get strange 

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```


## Factors 

```{r}
sex_vec = factor(c('male','male','female','female'))

as.numeric(sex_vec)
```

do some releveling 

```{r}
sex_vec=fct_relevel(sex_vec,'male')

as.numeric(sex_vec)
```


## Revisit examples 

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) |> 
  html_table() |> 
  first() |>
  slice(-1) %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(cols = -State,
               names_to = "age_year",
               values_to = 'percent') %>% 
  separate(age_year, into = c('age','year'),sep = '\\(') %>% 
  mutate(
    year = str_replace(year,'\\)',''),
    percent=str_remove(percent,"[a-c]$"),
    percent=as.numeric(percent)
  )
```

```{r}
table_marj %>% 
  filter(age=='12-17') %>% 
  mutate(
    State=fct_reorder(State,percent)
  ) %>% 
  ggplot(aes(x=State,y=percent, colour = year))+
  geom_point()+ 
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

## NYC RRestuarnt Inspections

```{r}
data('rest_inspec')

```

```{r}
rest_inspec %>% 
  count(boro,grade) %>% 
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```

```{r}
rest_inspec =
  rest_inspec %>% 
  filter(
    str_detect(grade,"[A-C]"),
    !(boro=='Missing')
  )
```

```{r}
rest_inspec %>% 
  mutate(dba=str_to_sentence(dba)) %>% 
  filter(str_detect(dba,'Pizza'))
```

```{r}
rest_inspec %>% 
  mutate(dba=str_to_sentence(dba)) %>% 
  filter(str_detect(dba,'Pizza')) %>% 
  mutate(boro=fct_infreq(boro)) %>% 
  ggplot(aes(x=boro))+geom_bar()
```

```{r}
rest_inspec %>% 
  mutate(dba=str_to_sentence(dba)) %>% 
  filter(str_detect(dba,'Pizza')) %>% 
  mutate(boro=fct_infreq(boro),
         boro=fct_recode(boro, "THE CITY"="MANHATTAN")) %>% 
  ggplot(aes(x=boro))+geom_bar()
```

One last thing on factors 
```{r}
rest_inspec %>% 
   mutate(dba=str_to_sentence(dba)) %>% 
  filter(str_detect(dba,'Pizza')) %>% 
  lm(zipcode~boro,data = .)
```

